name: 07 - Using Expressions

run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

on:
  # push:

  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Print start-up data
        if: inputs.debug == true
        run: |
          echo "Event name: ${{github.event_name}}"
          echo "Ref: ${{github.ref}}"
          echo "SHA: ${{github.sha}}"
          echo "Actor: ${{github.actor}}"
          echo "Workflow: ${{github.workflow}}"
          echo "Runner OS: ${{runner.os}}"

      - name: Print when triggered from main
        if: inputs.debug == true && github.ref == 'refs/heads/main'
        run: echo "I was triggered from main"

      - name: Greeting
        run: echo "Hello World"
